// Portfolio data — single source of truth.
window.PORTFOLIO = {
  name: "Zahra (Shadi) Khodagholi",
  handle: "shadi97kh",
  role: "PhD student, Industrial Engineering — University of Central Florida",
  advisor: { name: "Dr. Niloofar Yousefi", url: "https://www.cecs.ucf.edu/faculty/niloofar-yousefi/" },
  location: "Orlando, FL",
  bio: "Deep learning for biomedicine. Currently working on siRNA therapeutic design, saliency-based interpretability, and graph neural networks for spatial omics. I build methods that bridge ML with biological domain knowledge — biology-informed regularization for RNA therapeutics, and spatiotemporal models for real-time clinical applications.",
  research_areas: [
    { tag: "siRNA design",         note: "biology-informed regularization" },
    { tag: "interpretability",     note: "perturbation-based saliency faithfulness" },
    { tag: "graph neural nets",    note: "GNNs for spatial omics & molecular graphs" },
    { tag: "medical imaging",      note: "ultrasound landmark tracking, mammography seg." },
  ],
  links: {
    email: "zahra.khodagholi@ucf.edu",
    cv: "data/Zahra_PhD_CV.pdf",
    github: "https://github.com/shadi97kh/",
    linkedin: "https://www.linkedin.com/in/shadi97kh/",
    scholar: "https://scholar.google.com/citations?view_op=list_works&hl=en&user=DNgvArEAAAAJ",
    orcid: "https://orcid.org/0009-0004-6015-5300",
    goodreads: "https://www.goodreads.com/user/show/84959939",
    letterboxd: "https://boxd.it/4oQWr",
  },
  education: [
    { school: "University of Central Florida", logo: "images/UCF-logo.png",
      degree: "Ph.D., Industrial Engineering",
      span: "May 2025 — present", detail: "GPA 3.77 / 4.0", where: "Orlando, USA" },
    { school: "University of Central Florida", logo: "images/UCF-logo.png",
      degree: "M.S., Computer Science",
      span: "Sept 2022 — May 2025", detail: "GPA 3.70 / 4.0", where: "Orlando, USA" },
    { school: "Al-Zahra University", logo: "images/alzahra-logo.png",
      degree: "B.S., Computer Engineering",
      span: "Sept 2016 — Aug 2020", detail: "GPA 16.18 / 20 · Junior–Senior 17.17 / 20", where: "Tehran, Iran" },
  ],
  papers: [
    {
      id: "bioprior",
      title: "Validating Interpretability in siRNA Efficacy Prediction",
      subtitle: "A Perturbation-Based, Dataset-Aware Protocol",
      venue: "MLGenX Workshop @ ICLR 2026",
      year: "2026",
      authors: ["Zahra Khodagholi", "Niloofar Yousefi"],
      tldr: "Saliency maps for siRNA models can be faithful but wrong, or even inverted, when datasets shift. We introduce a perturbation protocol that catches this — and a biology-informed regularizer (BioPrior) that fixes it across four benchmarks.",
      abstract: "Gradient-based saliency is widely used to guide siRNA sequence design, but its reliability under distribution shift is rarely tested. We propose a perturbation-based faithfulness protocol and run it across four siRNA efficacy benchmarks. Cross-dataset transfer reveals two novel failure modes — faithful-but-wrong saliency and inverted saliency — showing that assay-protocol shifts can silently invalidate both predictions and their explanations. We then introduce BioPrior, a biology-informed regularizer that strengthens saliency faithfulness without hurting predictive accuracy.",
      figure: "bioprior",
      links: [
        { label: "arXiv",      href: "https://arxiv.org/abs/2602.10152" },
        { label: "OpenReview", href: "https://openreview.net/forum?id=0WStQt1qw5" },
        { label: "code",       href: "https://github.com/shadi97kh/BioPrior" },
      ],
    },
    {
      id: "ultra-air",
      title: "ULTRA-AIR: Ultrasound Landmark Tracking for Real-time Anatomical Airway Identification",
      subtitle: "and Reliability Check",
      venue: "IEEE Body Sensor Networks 2024",
      year: "2024",
      authors: ["Zahra Khodagholi", "Jasmine Sun", "Nour Awad", "Gregory R. Dion", "Laura J. Brattain"],
      tldr: "A deep-learning system that tracks neck landmarks live on ultrasound to assist airway management, with per-frame uncertainty so clinicians know when to trust it.",
      abstract: "ULTRA-AIR is a real-time deep-learning system for tracking anatomical landmarks of the neck on ultrasound video to assist with ultrasound-guided airway management. The model achieves high accuracy across landmark classes and computes per-frame uncertainty scores so the system can flag low-confidence predictions in critical-care settings.",
      figure: "ultra-air",
      links: [
        { label: "IEEE Xplore", href: "https://ieeexplore.ieee.org/abstract/document/10780557/" },
        { label: "code",        href: "https://github.com/shadi97kh/ULTRA-AIR" },
      ],
    },
  ],
  experience: [
    { role: "Machine Learning Solution Architect Intern", org: "BrainChip, Inc.", logo: "images/Brainchip.png",
      span: "Jun — Sept 2025",
      detail: "Spatio-temporal vision models on BrainChip's hardware-accelerated TENNs (Temporal Event-based Neural Networks). Evaluated TENNs for efficient object detection and segmentation, optimized for edge AI deployment on Akida neuromorphic processors." },
    { role: "Research Assistant", org: "University of Central Florida", logo: "images/UCF-logo.png",
      span: "Sept 2022 — present",
      detail: "Mammography image analysis with advanced segmentation models for early detection of breast cancer." },
    { role: "Teaching Assistant", org: "University of Central Florida", logo: "images/UCF-logo.png",
      span: "Aug 2023 — Dec 2024",
      detail: "Labs and grading for COP3503 (Computer Science II) and CNT4603 (System Administration)." },
    { role: "Computer Vision Intern", org: "Boston University", logo: "images/BU.png",
      span: "Jul — Dec 2021",
      detail: "Medical image segmentation tools for detecting COVID-19 in pediatric lung scans." },
    { role: "Machine Learning Intern", org: "ToobaTech · Al-Zahra AI Lab", logo: "images/Toobatech.png",
      span: "Aug 2019 — Jul 2020",
      detail: "Applied K-means, Random Forest, and regression models on real-world data; data preprocessing and insight generation." },
  ],
  projects: [
    { title: "Breast Cancer Segmentation", span: "Mar — May 2024",
      detail: "UNET architecture with MONAI on the TIGER dataset, focused on improving segmentation accuracy for early detection.",
      stack: ["UNET", "MONAI", "TIGER"],
      link: "https://github.com/shadi97kh/breast-cancer-segmentation" },
    { title: "Branch Prediction with CNNs", span: "Feb — Apr 2023",
      detail: "Designed a CNN-based branch predictor and benchmarked it against Gshare and bimodal predictors in computer-architecture simulations.",
      stack: ["CNN", "Gshare", "ChampSim"],
      link: null },
    { title: "Improving Spage2Vec", span: "Feb — Apr 2023",
      detail: "Under Haiyan Hu at UCF — hyperparameter exploration to improve Spage2Vec's accuracy on spatial gene-expression constellations.",
      stack: ["GraphSAGE", "spatial omics"],
      link: "https://github.com/shadi97kh/spage2vec" },
    { title: "Object Detection with ResNet", span: "Sept 2019 — Jul 2020",
      detail: "Bachelor's thesis. Trained ResNet/RetinaNet on COCO with a focus on accuracy and training-speed gains via pre-trained backbones.",
      stack: ["ResNet", "RetinaNet", "COCO"],
      link: "https://github.com/shadi97kh/Object-Detection-Using-Retinanet-Pretrained-model-on-COCO-Dataset" },
  ],
  reading: {
    books: [
      { title: "The Stranger",                author: "Camus",        color: "#c97064" },
      { title: "The Brothers Karamazov",      author: "Dostoevsky",   color: "#3d5a6c" },
      { title: "Crime and Punishment",        author: "Dostoevsky",   color: "#7a3b3b" },
      { title: "The Idiot",                   author: "Dostoevsky",   color: "#5c4a3a" },
      { title: "Zorba the Greek",             author: "Kazantzakis",  color: "#d4a04c" },
      { title: "Colorless Tsukuru Tazaki",    author: "Murakami",     color: "#6b8e7f" },
    ],
    watching: [
      { title: "Ikiru",            director: "Kurosawa",    year: 1952, kind: "film" },
      { title: "Taste of Cherry",  director: "Kiarostami",  year: 1997, kind: "film" },
      { title: "Fleabag",          director: "PWB",         year: 2016, kind: "series" },
    ],
    quote: "Reading and watching are how I keep biology in a head that mostly thinks in equations.",
  },
};
